### PR TITLE
Fix default value when missing translation

### LINKED ISSUE #4: Site not working for pt-br when missing translation
When accessing the clojure camp exercise site it shows just a blank page and throws an error in the console:
Image

This is because it was created a new exercise just with the `en-US` version and the default is not considering that the new structure has a map on it. 

I'll send a PR fixing that.

### PR DESCRIPTION
**Pull request by afucher**
Fixes #4 

Changed the default value on i18n to get `:en-US` as default value

ASAP I'll translate the new exercises to `pt-BR` 😇

### CODE REVIEW

File: src/exercise_ui/client/i18n.cljs [hunk 1]
```diff
@@ -18,4 +18,4 @@
   (reset! language lang))
 
 (defn value [i18n-map]
-  (get i18n-map @language i18n-map))
+  (get i18n-map @language (:en-US i18n-map)))
```
Comment (afucher) [inline src/exercise_ui/client/i18n.cljs:21]: Also thought to add something more robust to try to avoid errors at all, like 
```clojure
(or (:en-US i18n-map)
      "missing translation")
```

But I prefer to throw an error and we know that is missing, or we have an issue with the translation structure itself so we can fix, rather than show a default text and maybe have a confuse UX for the user.

**Comment by rafd** [comment]
Good catch. Returning en-US is fine. We have a validation function now for exercises to catch malformed input (but a missing translation is not considered malformed).
